import java.util.*;
import java.io.File;
import java.io.FileNotFoundException;  
import java.io.FileWriter;   // Import the FileWriter class
import java.io.IOException;  // Import the IOException class to handle errors	

class Filter
{	
	/* CYRILLIC alpahbet in unicode 
	 *	0410	А	CYRILLIC CAPITAL LETTER A					0430	а	CYRILLIC SMALL LETTER A	 
	 *	0411	Б	CYRILLIC CAPITAL LETTER BE					0431	б	CYRILLIC SMALL LETTER BE	 
	 *	0412	В	CYRILLIC CAPITAL LETTER VE					0432	в	CYRILLIC SMALL LETTER VE	 
	 *	0413	Г	CYRILLIC CAPITAL LETTER GHE					0433	г	CYRILLIC SMALL LETTER GHE	 
	 *	0414	Д	CYRILLIC CAPITAL LETTER DE					0434	д	CYRILLIC SMALL LETTER DE	 
	 *	0415	Е	CYRILLIC CAPITAL LETTER IE					0435	е	CYRILLIC SMALL LETTER IE	 
	 *	0416	Ж	CYRILLIC CAPITAL LETTER ZHE					0436	ж	CYRILLIC SMALL LETTER ZHE	 
	 *	0417	З	CYRILLIC CAPITAL LETTER ZE					0437	з	CYRILLIC SMALL LETTER ZE	 
	 *	0418	И	CYRILLIC CAPITAL LETTER I					0438	и	CYRILLIC SMALL LETTER I	 
	 *	0419	Й	CYRILLIC CAPITAL LETTER SHORT I	0418 0306	0439	й	CYRILLIC SMALL LETTER SHORT I	0438 0306	 
	 *	041A	К	CYRILLIC CAPITAL LETTER KA					043A	к	CYRILLIC SMALL LETTER KA	 
	 *	041B	Л	CYRlab1ILLIC CAPITAL LETTER EL				043B	л	CYRILLIC SMALL LETTER EL	 
	 *	041C	М	CYRILLIC CAPITAL LETTER EM					043C	м	CYRILLIC SMALL LETTER EM	 
	 *	041D	Н	CYRILLIC CAPITAL LETTER EN					043D	н	CYRILLIC SMALL LETTER EN	 
	 *	041E	О	CYRILLIC CAPITAL LETTER O					043E	о	CYRILLIC SMALL LETTER O	 
	 *	041F	П	CYRILLIC CAPITAL LETTER PE					043F	п	CYRILLIC SMALL LETTER PE	 
	 *	0420	Р	CYRILLIC CAPITAL LETTER ER					0440	р	CYRILLIC SMALL LETTER ER	 
	 *	0421	С	CYRILLIC CAPITAL LETTER ES					0441	с	CYRILLIC SMALL LETTER ES	 
	 *	0422	Т	CYRILLIC CAPITAL LETTER TE					0442	т	CYRILLIC SMALL LETTER TE	 
	 *	0423	У	CYRILLIC CAPITAL LETTER U					0443	у	CYRILLIC SMALL LETTER U	 
	 *	0424	Ф	CYRILLIC CAPITAL LETTER EF					0444	ф	CYRILLIC SMALL LETTER EF	 
	 *	0425	Х	CYRILLIC CAPITAL LETTER HA					0445	х	CYRILLIC SMALL LETTER HA	 
	 *	0426	Ц	CYRILLIC CAPITAL LETTER TSE					0446	ц	CYRILLIC SMALL LETTER TSE	 
	 *	0427	Ч	CYRILLIC CAPITAL LETTER CHE					0447	ч	CYRILLIC SMALL LETTER CHE	 
	 *	0428	Ш	CYRILLIC CAPITAL LETTER SHA					0448	ш	CYRILLIC SMALL LETTER SHA	 
	 *	0429	Щ	CYRILLIC CAPITAL LETTER SHCHA				0449	щ	CYRILLIC SMALL LETTER SHCHA	 
	 *	042A	Ъ	CYRILLIC CAPITAL LETTER HARD SIGN			044A	ъ	CYRILLIC SMALL LETTER HARD SIGN	 
	 *	042B	Ы	CYRILLIC CAPITAL LETTER YERU				044B	ы	CYRILLIC SMALL LETTER YERU	 
	 *	042C	Ь	CYRILLIC CAPITAL LETTER SOFT SIGN			044C	ь	CYRILLIC SMALL LETTER SOFT SIGN	 
	 *	042D	Э	CYRILLIC CAPITAL LETTER E					044D	э	CYRILLIC SMALL LETTER E	 
	 *	042E	Ю	CYRILLIC CAPITAL LETTER YU					044E	ю	CYRILLIC SMALL LETTER YU	 
	 *	042F	Я	CYRILLIC CAPITAL LETTER YA					044F	я	CYRILLIC SMALL LETTER YA
	 *	0401	Ё	CYRILLIC CAPITAL LETTER IO	0415 0308		0451	ё	CYRILLIC SMALL LETTER IO	0435 0308
	 *
	 *	0020	' '	WHITESPACE 
	*/

	public static String filterText(String str, boolean whitespaces)
	{	
		try	{
			String temp = str.replaceAll("\u044A", "\u044C");	//  ъ на ь
			temp = str.replaceAll("\u0451", "\u0435");			//	ё на е
			if (whitespaces)
				return temp.replaceAll("[^\u0430-\u044f\u0020]", "");
			else if (whitespaces == false)
				return temp.replaceAll("[^\u0430-\u044f]", "");
		} 
		catch (InputMismatchException e) {
			System.out.println("Invalid input!");
		}
		System.exit(-1);
		return "";
	}
}
